[project]
name = "agentic-recruitment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docling>=2.70.0",
    "jinja2>=3.1.6",
]
